"""Offline regressions for PostgreSQL migration foundation stages 1-4."""

import hashlib
import os
import re
import sqlite3
import tempfile
import unittest
from contextlib import closing, contextmanager, redirect_stdout
from io import StringIO
from pathlib import Path
from unittest.mock import patch

from scripts import migrate_sqlite_to_postgres as migration
from scripts import validate_sqlite_postgres_parity as parity
from src import database
from src import postgres_contract


ROOT = Path(__file__).resolve().parents[1]
POSTGRES_SCHEMA = ROOT / "db" / "schema_postgres.sql"
REAL_DB = ROOT / "topik-past-papers" / "derived" / "035-I-B.sqlite"


class PostgreSQLFoundationTests(unittest.TestCase):
    @staticmethod
    def _check_expressions(sql: str):
        expressions = []
        for match in re.finditer(r"\bCHECK\s*\(", sql, flags=re.I):
            start = sql.find("(", match.start())
            depth = 0
            quote = False
            index = start
            while index < len(sql):
                char = sql[index]
                if quote:
                    if char == "'":
                        if index + 1 < len(sql) and sql[index + 1] == "'":
                            index += 2
                            continue
                        quote = False
                else:
                    if char == "'":
                        quote = True
                    elif char == "(":
                        depth += 1
                    elif char == ")":
                        depth -= 1
                        if depth == 0:
                            expressions.append(sql[start + 1:index])
                            break
                index += 1
        return sorted("".join(item.split()).lower() for item in expressions)

    def test_postgres_schema_covers_all_migration_tables_and_append_only_audit(self):
        text = POSTGRES_SCHEMA.read_text(encoding="utf-8")
        sqlite_text = (ROOT / "db" / "schema.sql").read_text(encoding="utf-8")
        for table in migration.TABLES:
            self.assertIn(f"CREATE TABLE IF NOT EXISTS {table} (", text)
        for table in migration.OPTIONAL_SOURCE_TABLES:
            self.assertIn(f"'{table}'", text)
        self.assertIn("BYTEA NOT NULL", text)
        self.assertIn("GENERATED BY DEFAULT AS IDENTITY", text)
        self.assertIn("BEFORE UPDATE OR DELETE", text)
        self.assertIn("topik_reject_ai_audit_mutation", text)
        normalized = "".join(text.lower().split())
        self.assertIn("raiseexception'aiaudittablesareappend-only'", normalized)
        self.assertIn("errcode='55000'", normalized)
        self.assertNotIn("PRAGMA", text)
        # Schema shape must not silently drop key/constraint/index contracts.
        token = lambda pattern, value: re.findall(pattern, value, flags=re.I | re.M)
        self.assertEqual(
            len(token(r"\bPRIMARY\s+KEY\b", text)),
            len(token(r"\bPRIMARY\s+KEY\b", sqlite_text)),
        )
        self.assertEqual(
            len(token(r"\bUNIQUE\s*\(", text)),
            len(token(r"\bUNIQUE\s*\(", sqlite_text)),
        )
        self.assertEqual(
            len(token(r"\bCHECK\s*\(", text)),
            len(token(r"\bCHECK\s*\(", sqlite_text)),
        )
        self.assertEqual(
            sorted(token(r"REFERENCES\s+(\w+)\s*\(\s*(\w+)\s*\)", text)),
            sorted(token(r"REFERENCES\s+(\w+)\s*\(\s*(\w+)\s*\)", sqlite_text)),
        )
        self.assertEqual(
            sorted(token(r"CREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+(\w+)", text)),
            sorted(token(r"CREATE\s+INDEX\s+IF\s+NOT\s+EXISTS\s+(\w+)", sqlite_text)),
        )
        # The PostgreSQL port keeps the CHECK expressions themselves, not only
        # their count. These expressions are deliberately SQL-common syntax.
        self.assertEqual(self._check_expressions(text), self._check_expressions(sqlite_text))
        self.assertEqual(
            set(postgres_contract._postgres_expected_columns()),
            set(migration.TABLES),
        )
        self.assertEqual(
            set(postgres_contract._sqlite_contract()),
            set(migration.TABLES),
        )

    def test_append_only_function_definition_contract_matches_postgres_rendering(self):
        rendered = """CREATE OR REPLACE FUNCTION public.topik_reject_ai_audit_mutation()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
    RAISE EXCEPTION 'ai audit tables are append-only' USING ERRCODE = '55000';
END;
$function$
"""
        self.assertTrue(postgres_contract._append_only_function_definition_is_valid(rendered))
        self.assertFalse(
            postgres_contract._append_only_function_definition_is_valid(
                rendered.replace("55000", "22000")
            )
        )

    def test_migration_rejects_preexisting_topik_target_table(self):
        class Result:
            def fetchall(self):
                return [{"table_name": "questions"}]

        class FakePostgres:
            def execute(self, statement, params=None):
                return Result()

        with self.assertRaisesRegex(migration.MigrationError, "fresh schema/database"):
            migration._target_must_be_unused(FakePostgres())

    def test_database_configuration_is_additive_and_media_root_is_configurable(self):
        with patch.dict(os.environ, {}, clear=False):
            os.environ.pop(database.DATABASE_URL_ENV, None)
            os.environ.pop(database.MEDIA_ROOT_ENV, None)
            self.assertIsNone(database.get_database_url())
            self.assertEqual(database.get_media_root(), database.DEFAULT_MEDIA_ROOT.resolve())
        with tempfile.TemporaryDirectory(prefix="topik-media-root-") as tmp:
            with patch.dict(os.environ, {
                database.DATABASE_URL_ENV: "postgresql://example.invalid/topik",
                database.MEDIA_ROOT_ENV: tmp,
            }, clear=False):
                self.assertEqual(
                    database.get_database_url(), "postgresql://example.invalid/topik"
                )
                self.assertEqual(database.get_media_root(), Path(tmp).resolve())
        with patch.dict(os.environ, {database.DATABASE_URL_ENV: "sqlite:///bad"}, clear=False):
            with self.assertRaises(database.DatabaseConfigError):
                database.get_database_url(required=True)

    def test_qmark_translation_preserves_literal_question_marks(self):
        sql = "SELECT * FROM questions WHERE id=? AND stem='정말?' AND raw_question_text=\"?\""
        self.assertEqual(
            database.qmark_to_postgres(sql),
            "SELECT * FROM questions WHERE id=%s AND stem='정말?' AND raw_question_text=\"?\"",
        )

    def test_postgres_read_connection_sets_session_default_read_only(self):
        class FakeError(Exception):
            pass

        class RawConnection:
            def __init__(self):
                self.statements = []
                self.commits = 0

            def execute(self, statement, params=None):
                self.statements.append((statement, params))
                return self

            def commit(self):
                self.commits += 1

            def close(self):
                pass

        raw = RawConnection()

        class FakePsycopg:
            Error = FakeError

            @staticmethod
            def connect(url, *, autocommit, row_factory):
                self.assertEqual(url, "postgresql://fixture.invalid/topik")
                self.assertFalse(autocommit)
                return raw

        with patch.object(database, "_psycopg", return_value=(FakePsycopg, object())):
            connection = database.connect_postgres(
                "postgresql://fixture.invalid/topik", readonly=True
            )
        self.assertIs(connection, raw)
        self.assertEqual(raw.statements, [("SET default_transaction_read_only = on", None)])
        self.assertEqual(raw.commits, 1)

    def test_sqlite_readonly_rejects_writes(self):
        with tempfile.TemporaryDirectory(prefix="topik-readonly-") as tmp:
            path = Path(tmp) / "test.sqlite"
            with closing(sqlite3.connect(path)) as db:
                db.execute("CREATE TABLE sample(id INTEGER PRIMARY KEY, value TEXT)")
                db.execute("INSERT INTO sample(value) VALUES('unchanged')")
                db.commit()
            before = hashlib.sha256(path.read_bytes()).hexdigest()
            with database.sqlite_readonly(path) as db:
                self.assertTrue(db.in_transaction)
                self.assertEqual(db.execute("SELECT value FROM sample").fetchone()[0], "unchanged")
                with self.assertRaises(sqlite3.OperationalError):
                    db.execute("UPDATE sample SET value='changed'")
            self.assertEqual(hashlib.sha256(path.read_bytes()).hexdigest(), before)

    @unittest.skipUnless(REAL_DB.is_file(), "Private 35-I SQLite database is not installed")
    def test_real_source_dry_run_matches_approved_baseline_without_mutation(self):
        before = hashlib.sha256(REAL_DB.read_bytes()).hexdigest()
        summary = migration.inspect_source(REAL_DB, require_baseline=True)
        after = hashlib.sha256(REAL_DB.read_bytes()).hexdigest()
        self.assertEqual(after, before)
        self.assertEqual(summary["integrity_check"], "ok")
        self.assertEqual(summary["foreign_key_violations"], 0)
        self.assertEqual(summary["counts"]["questions"], 70)
        self.assertEqual(summary["review_status"], {"needs_manual_review": 68, "verified": 2})
        self.assertEqual(summary["counts"]["review_records"], 124)
        self.assertEqual(summary["candidate_audio"], 30)
        self.assertEqual(
            set(summary["tables_absent_optional"]), migration.OPTIONAL_SOURCE_TABLES
        )

    @unittest.skipUnless(REAL_DB.is_file(), "Private 35-I SQLite database is not installed")
    def test_source_only_parity_hashes_rows_and_blobs_without_postgres(self):
        before = hashlib.sha256(REAL_DB.read_bytes()).hexdigest()
        output = StringIO()
        with redirect_stdout(output):
            code = parity.main(["--source", str(REAL_DB), "--source-only"])
        self.assertEqual(code, 0, output.getvalue())
        self.assertIn('"status": "source-ok"', output.getvalue())
        self.assertIn('"image_blob_sha256_failures": []', output.getvalue())
        self.assertEqual(hashlib.sha256(REAL_DB.read_bytes()).hexdigest(), before)

    @unittest.skipUnless(REAL_DB.is_file(), "Private 35-I SQLite database is not installed")
    def test_migration_rolls_back_target_transaction_on_insert_failure(self):
        class Result:
            def fetchone(self):
                return {"count": 0}

            def fetchall(self):
                return []

        class Cursor:
            def __enter__(self):
                return self

            def __exit__(self, exc_type, exc, tb):
                return False

            def executemany(self, statement, rows):
                raise RuntimeError("simulated PostgreSQL insert failure")

        class FakePostgres:
            def __init__(self):
                self.committed = False
                self.rolled_back = False

            def execute(self, statement, params=None):
                if "information_schema.tables" in statement:
                    return Result()
                if statement.lstrip().upper().startswith("SELECT COUNT(*) AS COUNT FROM"):
                    return Result()
                return Result()

            def cursor(self):
                return Cursor()

            def commit(self):
                self.committed = True

            def rollback(self):
                self.rolled_back = True

        pg = FakePostgres()

        @contextmanager
        def fake_connection(_url):
            yield pg

        before = hashlib.sha256(REAL_DB.read_bytes()).hexdigest()
        with patch.object(migration, "get_database_url", return_value="postgresql://test.invalid/topik"), \
             patch.object(migration, "postgres_connection", side_effect=fake_connection), \
             patch.object(migration, "validate_postgres_structure", return_value=[]):
            with self.assertRaisesRegex(RuntimeError, "simulated PostgreSQL insert failure"):
                migration.migrate(REAL_DB, require_baseline=True)
        self.assertTrue(pg.rolled_back)
        self.assertFalse(pg.committed)
        self.assertEqual(hashlib.sha256(REAL_DB.read_bytes()).hexdigest(), before)


if __name__ == "__main__":
    unittest.main()
